### ISSUE TITLE
divide by zero encountered in float_scalars

### ISSUE THREAD

**Issue by osowiecki** [J35P312/TIDDIT#10]
working on seqence B73V4_ctg204
working on seqence B73V4_ctg22
working on seqence B73V4_ctg228
working on seqence B73V4_ctg27
working on seqence B73V4_ctg116
working on seqence B73V4_ctg126
working on seqence B73V4_ctg237
working on seqence B73V4_ctg187
working on seqence B73V4_ctg76
signal extraction time consumption= 1181s
./TIDDIT.py:77: RuntimeWarning: divide by zero encountered in float_scalars
  TIDDIT_calling.cluster(args)

**Comment by J35P312** [comment]
Hello there!
These warnings are messy! But mostly harmless, and usually occur during the coverage normalization step when treating low quality contigs.
I'm working on silencing these warning messages as they are found, but this is not a priority.

If you have run in to some sort of error, feel free to post that error. 
Good luck!
