### ISSUE TITLE
Error on conda installation

### ISSUE THREAD

**Issue by fanavarro** [J35P312/TIDDIT#12]
I've just installed TIDDIT in a fresh bioconda environment, but I am not able to execute the application due to the following error:

`error,  could not find the TIDDIT executable file, try rerun the INSTALL.sh script`

I have researched a little on this, and it seems to be that the executable file is next to the python script in the bin folder inside the conda environment folder (some results are omitted due to readability):

```
(tiddit) user@server:~/anaconda3/envs/tiddit$ find . -iname "tiddit*"
./bin/TIDDIT
./bin/TIDDIT.py
./bin/tiddit
```

However, the python script is trying to find the executable in `{python_script_location}/bin/TIDDIT`, which results in `~/anaconda3/envs/tiddit/bin/bin/TIDDIT`. Then the executable is not found and the application fails.

I think the python script is expecting a folder structure similar to when you build the application from the source code, however this structure is different when you install the app through conda.

**Comment by J35P312** [comment]
Hello!
And thanks for giving the conda installation a try!
I will have a look and see if I can fix this

Best regards
Jesper

**Comment by maxulysse** [comment]
I'd say that it is now fixed:
https://github.com/bioconda/bioconda-recipes/pull/35167

**Comment by J35P312** [comment]
I agree, this is fixed =P
