### ISSUE TITLE
Which is the main repo?

### ISSUE THREAD

**Issue by maxulysse** [J35P312/TIDDIT#17]
I noticed that there was some releases missing in https://github.com/J35P312/TIDDIT and in https://github.com/SciLifeLab/TIDDIT
Which repo is now the main one?
Can we get some clarification on that so that we can keep the bionconda recipe up to date and hopefully working?

**Comment by J35P312** [comment]
Hello!
Sorry for the confusion =P. It should be https://github.com/SciLifeLab/TIDDIT.
I lost my permission to write to the SciLifeLab repo, that's why I had to switch to my own fork for a while. but now everything is working again. Thanks for helping with the bioconda!
