### ISSUE TITLE
Replace outfile_prefix in VARID with sample id

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/TIDDIT#3]
VARID=SV_4_2:ADM1059A2_lanes_8_sorted_md_brecal_tiddit

would be shorter and just as unique as:

VARID=SV_4_2:ADM1059A2

right?

**Comment by henrikstranneheim** [comment]
Ops, This should have been in svdb correct?

**Comment by J35P312** [comment]
Hello that's a good idea, I will do so!
