### ISSUE TITLE
Vcf header line ##LibraryStats Coverage

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/TIDDIT#4]
Would it be possible to follow the convention of having key=value pairs in the vcf header. The LibraryStats line is throwing errors downstream of TIDDIT.

From the vcf spec:
"File meta-information is included after the ## string and must be key=value pairs. "

**Comment by J35P312** [comment]
Aloha!
Sorry about that, I have now fixed it:
##LibraryStats=TIDDIT Coverage=3.40804 ReadLength=86 MeanInsertSize=3045 STDInsertSize=1347 Orientation=outtie
Feel free to try it again!
By the way, I will come back to the rest of the issues on friday!

**Comment by J35P312** [comment]
I also made a new release 1.1.2
